version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - 'oguzhanyamak'
    labels:
      - 'dependencies'
      - 'javascript'

  # Enable version updates for Rust dependencies
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - 'oguzhanyamak'
    labels:
      - 'dependencies'
      - 'rust'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'